/*
* Generated file
*
* Generated from: yang module name: task-provider-impl yang module local name: task-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Jul 09 19:47:35 IST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.task_provider.impl;
public class TaskProviderModuleFactory extends org.opendaylight.controller.config.yang.config.task_provider.impl.AbstractTaskProviderModuleFactory {

}
